### ISSUE TITLE
Error with nextjs12

### ISSUE THREAD

**Issue by njarraud** [nickbabcock/next.js-wasm-worker#1]
Hello,
This example doesn't seem to work anymore (Nextjs 12.0).
I was wondering if there was a quick solution to make it work.

<img width="452" alt="Capture d’écran 2021-11-06 à 19 35 11" src="https://user-images.githubusercontent.com/45501180/140600389-bcde9cf5-a6e8-442c-86ae-ea98e6adde5b.png">

**Comment by nickbabcock** [comment]
Wow, so disheartening. I was looking to move to nextjs12 but now I'm not sure. I can replicate your issue, but I couldn't figure out a quick solution. I'll need to do some more investigation.

**Comment by njarraud** [comment]
I finally managed to make it work. I simply replaced **await import** by **await require**

**Comment by nickbabcock** [comment]
Great solution! I have no idea why this behavior changed, but good catch. I've updated the repo to be compatible with nextjs12
